### ISSUE TITLE
Setting text style without color throws nil pointer exception

### ISSUE THREAD

**Issue by ribice** [unidoc/unidoc#296] opened 2019-01-06 15:41 UTC
I used a bit different approach compared to the one from tests. From tests:

```
titleStyle := invoice.TitleStyle()
titleStyle.Color = blue
titleStyle.Font = fontHelvetica
titleStyle.FontSize = 30
invoice.SetTitleStyle(titleStyle)
```

To make it shorter, I tried setting it with:

```
invoice.SetTitleStyle(creator.TextStyle{
titleStyle.Color = blue
titleStyle.Font = fontHelvetica
titleStyle.FontSize = 30
})
```

If Color parameter is omitted, execution throws nil pointer exception.
It happens because Color is an interface, and when it is not set execution fails on calling `ToRGB` func.

Is this expected behavior? Can it be prevented?

**Comment by adrg** [comment] 2019-01-07 16:04
@ribice I think that the library should not panic. It's not expected behavior and it should be prevented.
On the other hand, the creator object has a method for instantiating a new, fully initialized TextStyle object. This method should be used in almost all cases.

The method can be found here: https://github.com/unidoc/unidoc/blob/v3/pdf/creator/creator.go#L601

```
	c := creator.New()
        style := c.NewTextStyle()
        style.FontSize = 30
        style.Color = blue
        ...
```

While I don't think the library should panic, I do feel that the user is responsible with fully initializing the text style object, if he chooses to do that manually.

@gunnsth Any thoughts on this? What is the desired behavior in case the user creates a TextStyle object manually and initializes it partially?

**Comment by gunnsth** [comment] 2019-01-08 00:37
Generally, we don't want to panic on user input error such as when parsing arbitrary PDF files, etc.

I think it's OK to panic if it is a programming error, should be pretty easy to find during development.  Unlikely this would come up in a production environment if the product has been tested.

The alternative would be to specify default values if not set, similar as done in c.NewTextStyle().  Presumably could use the same defaults. It would seem like the alternative approach would require a lot of checks in multiple places, so I am not sure whether it is feasible.

It would also be possible to unexport the fields and require the use of a constructor, or setter/getters.
I am not sure that is feasible either.  Currently seems to me that the early panic on programming error is acceptable.

**Comment by adrg** [comment] 2019-01-09 18:19
The first alternative is very tedious to implement and it would not produce very clean code.
The other alternative does represent a possible solution. However, the user will not be able pass TextStyle objects around in his own code.

Another solution would be to make TextStyle a public interface and have a textStyle private struct implementation of the TextStyle interface. In this case, the user will be forced to initialize TextStyle objects through the library method. This solution is also not perfect because then, all the fields of the TextStyle will be accessible only through methods whereas now they are easier to use through public fields.

If a panic is acceptable when coming from partial initialization of TextStyle objects, I think this issue can be closed.

**Comment by gunnsth** [comment] 2019-01-10 11:17
Agree.  Closing.

**Closed by gunnsth** 2019-01-10 11:17 UTC
